
const SermonDetails = [
 {key:1,
     content:`THE salvation of God that would come to all repentant sinners through  Jesus Christ as of grace was, since the days of Moses the prophet, typified by a very significant incident when a serpent of brass was set up for the Israelites.
     The children of Israel were a stubborn people. Because of their faithlessness, in spite of the wonders of the Almighty God they saw in Egypt, they continued to sin. On several occasions while they were journeying to Canaan they provoked God by reason of their abominable deeds, and they were justly punished. But when they repented and turned to God they received mercy.
     One of such occasions was after the death of Aaron when they journeyed from Mount Hor by way of the Red Sea to the land of Edom. And because they grew impatient over the route they began to open their mouths wide I against Heaven. As a result of this God sent dreadful serpents to assail the camp of Israel and I many people were bitten to death.
     Here is the Bible record:
     “And they (the Israelites) journeyed from mount Hor by the way of the Red Sea, to compass the land of Edom: and the soul of the people was much discouraged because of the way. And the people spake against God, and against Moses, Wherefore have ye brought us up out of Egypt to die in the wilderness? for there is no bread, neither is there any  water; and our soul loatheth this light bread. And the Lord sent fiery serpents among the people and they bit the people; and much people of Israel died.”- Numbers 21: 4-6.
     Following this plague the Israelites came to their senses and realised their faults. They went to Moses their leader to confess that they had sinned for speaking against God and against him (Moses). They pleaded with him to pray to the Most High to take away the- serpents from them.
     Moses who was well known for his godly disposition and kind-heartedness and humility, acceded to their request and he interceded on their behalf.
     God heard the prayer of Moses. It was really an easy thing for Him to remove the venomous snakes all at once but He did not. Rather, He commanded Moses, saying, “Make thee a fiery serpent, and set it upon a pole: and it shall come to pass, that every one that is bitten, when he looketh upon it, shall live.” – Numbers 21: 8.
     In obedience to the Lord’s instruction, Moses made a serpent of brass and erected it on a pole, “and it came to pass, that if a serpent had bitten any man, when he beheld the serpent of brass, he lived.”- Numbers 21: 9.
     
     
     
     All diligent students of the Bible do agree that the whole event which culminated in the erection of the brazen serpent was of great spiritual significance. There is quite a lot to learn from the experience of the Israelites and what God did to relieve them of their pains and to save them from death. Yes, it was Saint Paul who stated: “For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope.” – Romans 15: 4.
     Now, let us ask ourselves this question: why was Israel plagued with fiery serpents by the very God of their fathers who had done so much to aid them at the time of their distress and adversity? It is clear from the Bible account that it was because they sinned against God. They were guilty of blasphemy – a very serious offence!
     Today there are people who behave like the faithless Israelites. For every misfortune that befalls them they blame the cause on God.
     When they find themselves in any unfavourable situation they turn round to accuse God-notwithstanding the fact that such a situation is of their own making. There is also the class of those, especially among the intellectuals of the world, who take pride in talking glibly and irreverently about God.
     Men must learn to know that God is not the one responsible for their ills or troubles. The evils or tribulations that often come upon us are either due to our own sins of the devil, taking advantage of our “infirmities being human and especially because of our sensualism, brings them upon us.
     The temptation of Job is a striking example of how the devil can trouble even the man of God with the aim of making the person to curse God and so fallout of His favour. Under such circumstances, the true worshippers of God are required to maintain their integrity in faith as Job himself did, and then cry to God in prayer for help and deliverance. – Job 2: 3; 27: 4, 6; Proverbs 11: 3; James 5: 10,11.
     Salvation
     Speaking in the first person through Isaiah the prophet, God declared: “Look unto me, and be ye saved, all the ends of the earth: for I am God, and there is none else.” – Isaiah 45: 22.
     In order to fulfil His purpose of saving His people, God had to send His beloved Son, Jesus Christ, to the world not only to serve as a propitiation for the sins of mankind but also to be the Mediator through whom eternal life would be obtained in His glorious Kingdom. – 1 Timothy 2: 4-6; 1 John 2: 1, 2.
     Thus the brazen serpent, which God caused Moses to set up for snake-bitten Jews to look to and which served as a remedy for the plague of poisonous serpents, fore- shadowed Jesus Christ who would in due time be sent to the world  God for all mankind to look to for the healing of their  wounds and for their salvation.
     With this understanding at the back of his mind in regard to his mission on earth, Jesus Christ told Nicodemus concerning himself:
     “And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up: that whosoever believeth in him should not perish, but have eternal life.”- John 3: 14, 15.
     Jesus Christ further explained the reason why the Heavenly Father has made such a grand arrangement for the benefit of sinful mankind when he said: “For God so loved the world, that He gave His only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.” – John 3: 16.
     We must guard ourselves, by the grace of God, against sin. If the Israelites had not sinned they would not have been plagued. Therefore, sin, which is the transgressing of God’s commandment, is a great danger. “For the wages of sin,” said Saint Paul, “is death: but the gift of God is eternal life through Jesus Christ our Lord.”- Romans 6: 23.
     
     Antitypical
     
     It could be recalled that when the brazen serpent was erected on a pole in the days of Moses, the rule was that anyone who was bitten by a serpent would live only on the condition that he looked at the serpent of brass.
     We do know that since the setting up of the brazen serpent was typical, the looking at it was also literal – that is, it was the use of ordinary sight by way of turning the eyes, in the direction of the serpent of brass, of course, with the belief .that by so doing they were carrying out God’s instruction or command. But the case of Jesus Christ being antitypical, we are not expected to see him with our human eyes because he is now invisible being a spirit personality who has been glorified in heaven.
     Then, how do we look to Jesus Christ as to draw a parallel between the typical and antitypical? Christ himself gave the answer when he said, “That whosoever believeth in him should not perish, but have eternal life.” (John 3: 15) The key-word in this text is BELIEVETH. In other words what is required is belief or faith in Jesus Christ.
     As a matter of fact, Jesus Christ told Thomas one of his apostles: “Ye believe because you have seen me. Blessed be those who believe though they have never seen me.” (John 20: 29 – Moffatt) What is more, St. Paul stated: “For we walk by “faith, not by sight.” – 2 Corinthians 5: 7.
     So today, the benefits of Christ’s redemption and his salvation are obtainable]e only on the condition that we BELIEVE in him. “He that believeth on the Son (Jesus) hath everlasting life: and he that believeth not the Son shall not see life: but the wrath of God abideth on him.” John 3: 36.
     However, we must not deceive ourselves in thinking that our mere belief in Jesus Christ while we wallow in sins, indulging in sinful lusts of the eyes and flesh, or when we worship him loosely, will save us. IT WILL NOT. It is when we have IMPLICIT FAITH in and LOVE for him, which will make us keep his commandments unhesitatingly, accept his true doc- trines and abide in the Church organization which preaches his TRUTH unadulteratedly, that we are qualified to claim to have looked to or accepted Christ. – Matthew 7: 21; Luke 6: 46-49; John 14: 15, 21-25; 8: 31-32, 36.
     
     Exalted Jesus
     
     The position of Jesus Christ among the creation of God is unique-it is a position of honour, glory and pre-eminence. We must therefore accept him as our Saviour and exercise implicit faith in him as such.
     Peter the apostle, addressing the council of the Jews, spoke of the greatness of Jesus Christ when he quoted the Hebrew Scriptures which today is called the Old Testament, to wit: “This is the stone which was set at nought of you builders, which is become the head of the corner.” And he added: “Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.”- Acts 4: 10-12.
     Concerning the exaltation of Jesus Christ, St. Paul also wrote: “Wherefore God also hath highly exalted him (Jesus), and given him a name which is above every name: that at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things under the earth; and that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.”- Philippians 2: 9-11.
     Furthermore, St. Paul gave an exhortation to the Hebrew Christians, which, in fact, is directed to every true disciple of Jesus Christ throughout the Christian era. He warned that in running the race of life, we as Christians must put away sin and divest ourselves of the burdens of the world that would impede our spiritual progress. He then admonished, “And let us run with patience the race that is set before us, looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.”– Hebrews 12: 1,2.
     In the light of the Scripture texts clearly explained in this sermon, we are not left in doubt that our salvation is in our hands. Therefore, “work out your own salvation with fear and trembling.” – Philippians 2: 12.`,
      title:"THE BRAZEN SERPENT"},
 {key:2,
     content:`CHRISTIANITY is so fundamentally based and entrenched on established principles and doctrines that it cannot be blended or mixed with other beliefs without falling into the danger of corruption. This is what many people do not know.

     Interfaith is a mixture of beliefs – that is, people of different faiths coming together in a sort of union to worship.
     Ecumenism
     Today the wind of ecumenism is blowing all over Christendom. There is a strong desire by many church denominations to unite with others notwithstanding their differences in doctrines and forms of worship. For this reason certain churches have relaxed their rules which hitherto strictly forbade their adherents from having any form of communion with others.
     In pursuance of this same objective for church unity, the former Archbishop of Canterbury, Dr. Geoffrey Fisher, and his successor, Archbishop Michael Ramsey, had paid visits to both the late Pope John XXIII and Pope Paul VI, respectively, at the Vatican City. As a result of the meeting between Pope Paul and Archbishop Ramsey, 10 Roman Catholic and 11 Anglican theologians met together at Gazzada in Northern Italy, in January, 1967. They made recommendations for joint action on practical ways of removing tension between members of the two churches. A communiqué was issued after the talks which were described as the “first formal steps towards unity between the two churches in more than 400 years”. And the hopes of many people were raised!
     But three days after the talks, Pope Paul stated that Christian unity “still presents grave difficulties, for concept of real unity is not clear to all people.” He was speaking at his weekly blessing of pilgrims in St. Peter’s Square at the Vatican City. He said, “Some people consider that charity – which is certainly necessary – is enough for this unity without adhering to the unique truth of the faith.” (Daily Times, January 17, 1967)
     Catholic Idea
     Obviously, the Roman Catholic idea of church unity is quite different from what others are thinking. While some are reckoning it on terms of equal partners, the other is hoping that it is the coming back of the “separated brethren” to the one fold of the “Mother Church”.
     A Roman Catholic newspaper, the INDEPENDENT, issue of June 25-29, 1968, published at Ibadan, Western State of Nigeria, presented the Roman Catholic view on ecumenism as follows: “The word ECUMENISM is, it must be admitted, a rather difficult term for the ordinary Catholic to fully grasp or understand But we must be clear, first of all, as to what Ecumenism does not mean. It does not mean Eucharistic unity (i.e. we cannot regard the Holy Mass and a non-Catholic Communion Service as equal and interchangeable)..,..It does not mean a whittling down of Catholic doctrines to achieve a common faith with non-Catholics, for that would mean unfaithfulness to the Catholic Church as the ‘pillar and ground of Truth’,” (Italics ours).
     
     In answer to a question, the INDEPENDENT (June 20-27, 1964, page 5) stated: “Catholics ought not to attend non-Catholic religious functions. If they are present at public functions when non-Catholic prayers are said they ought not to answer ‘Amen’.”
     There is every reason to regard all the noise about the unification of all the churches as a show of spiritual ignorance on the part of some and sheer hypocrisy on the side of others. We do not see how a genuine unity can evolve from the attempts being made when nothing is being done to remove the root of bitterness and the cause of the division among them.
     In Amos 3: 3, it is written: “Can two walk together, except they be agreed?” Certainly, they cannot. It is a known fact that great differences in doctrines, church organisation and worship, exist among the churches. These have always been the main cause of controversy. Any union formed by the churches, therefore, with eyes closed upon these facts, is a union of contraries – and it is unchristian.
     Anglican Reply
     The Anglican Communion knows that the Roman Catholic Church does not regard it as an institution founded by God. The proof of this is evident from an Anglican reply to Roman Catholic arguments published in a booklet, the INFALLIBLE FALLACIES. The Anglican priests stated that some people of their parishes were being disturbed by the fact that the Roman Catholics regard them as non- Christians yet to be proselytised or converted and also by the repetition of untruths about their church. They added: “These untruths are part of the Roman Catholic campaign of trying to gain Anglicans for their own Church. Some of the most frequent of them are that ‘Henry VIII founded the Church of England’; that ‘Anglican bishops and priests are not real bishop!; and priests’ and that therefore ‘the sacraments administered in Anglican Churches are invalid!…We do not unchurch them, but they unchurch us. We regard the Pope as the lawful Bishop of Rome and their bishops and priests as properly consecrated and ordained, and their sacraments as valid. But they regard our bishops and priests as either deluded or deliberate impostors, and our sacraments as but imitations or mockeries of the divinely appointed channels of grace.” (Page 4, emphasis ours).
     No serious effort is known to have been made by the Anglican Communion to resolve or clear these GRAVE SPIRITUAL ISSUES before the efforts they are making WITHOUT REGARD FOR THE BIBLE – THE LAW AND GUIDE BOOK OF GOD – to get united with the Roman Catholic Church!
     Importance of Doctrines
     Another evidence of how strongly some people feel about the importance of doctrines in the worship of God was manifested when the Bishop of Rome declared the “bodily assumption of Mary” as an article of faith in 1950. It was reported that “nine British protestants wrote to Pope Pius XII offering to become Roman Catholics if he could produce a scriptural proof of the bodily assumption of the Virgin Mary.” (West African Pilot, October 30, 1950)
     
     So too, when the Swedish Church proposed to ordain women priests, the Church of England protested because it was considered to be scripturally wrong to do so. The then Archbishop of Canterbury, Dr. Fisher, sent a “personal and confidential” letter to the Archbishop of Sweden warning that “if Sweden ordains women priests, relations between the two churches will be broken off”. (Daily Sketch, January 15, 1959, published in England.)
     Yes, Dr. Fisher was right, for God has never ordained women to be priests. Even in the church women are commanded not to speak, or teach but “to be under obedience”. – 1 Corinthians 14: 34, 35; 1 Timothy 2: 11-14.
     The point is that all these go to emphasise the awareness of some of the churches about the importance of the doctrines on which the Christian Faith is based. And that was why an Anglican Chaplain, Rev. R. Earnshaw-Smith said that “unification of Protestant Church with the Roman Catholic Church ‘is impossible’, because there existed a number of fundamental doctrinal differences between the Anglican Church and the Roman Catholic Church’ . He added, “There are such things as truth and error.” (Nigerian Daily Express, May 16, 1962.)
     “Credo”
     Only of recent Pope Paul re-affirmed in his “Credo” the belief of the Roman Catholic Church in certain doctrines which have always been the bone of contention between them and others. The Pope stated: “We believe in the infallibility enjoyed by the successor of Peter…We believe that Mary is the mother, who remained ever a virgin…preserved from all the stain of original sin and filled with gift of grace more than all other creatures. We believe that the mysterious presence of the Lord (in the Eucharist) is a true, real and substantial presence…the bread and wine have ceased to exist after the consecration so that it is the adorable body and blood of the Lord Jesus.” (INDEPENDENT, July 21-27, 1968).
     Now there are several church groups that do not believe in the bodily assumption of Mary, her being a virgin forever or the “Mother of God”; they do not believe in purgatory, the celibacy of priests, man-made saints, baptism of infants, the bodily presence of Christ in the bread and wine, or hell being a place of literal fire, and so on. But the Roman Catholic Church believes in all these and some others also believe in some of them.
     The obvious fact is that all cannot be right while they are opposed to one another. So if the claims of the Roman Catholics are true in the sense that they are founded on the authority of the Holy Bible, which all accept as the Guide Book, then others who disagree with them are false, and vice versa. And if some are true and others false, then there is no basis whatsoever for real unity.
     Baptists’ Stand
     The stand of the Baptists is already known. Dr. William R. Tolbert, Jr., President of the Baptist World Alliance and Vice- President of the Republic of Liberia, stated: “Baptists are opposed to any church unity movement which would destroy their basic beliefs.” He added that Baptists “would not associate with any movement to set up a hierarchy to control and influence individual churches.” (African Challenge, No. 196, page 5).
     Here in Nigeria, efforts are also being made towards a “United Church of Nigeria”. The GKS is not a party to it PURELY on doctrinal and other scriptural grounds. And some church leaders of the orthodox groups have asked that their churches should be counted out too. It could be observed that all the obstacles undermining these efforts very well spring from the same variances in doctrines and methods of worship.
     In the October issue of the Spear magazine in 1965. The views of some of the religious leaders were published. Arch- bishop John Aggey of the Roman Catholic Church in Lagos said: “There will be more confusion if the Roman Catholic Church joins the union now because we have certain beliefs different from those of other sects. ”
     In the same issue of the Spear, Colonel John, the head of the Salvation Army in Nigeria, was quoted as saying, “We wish those who are planning to form the Union success. H they think that is the best thing for their churches, God bless them. The Salvation Army is not thinking about joining the Union at this stage because our constitution is different from those of other churches. For example, we have women as Ministers in our church while others don’t…”
     Now the Roman Catholic Church is not prepared to whittle down its doctrines and the Protestant groups also cannot buldge in their beliefs. So any union of all these in the face of the vast differences is but a marriage of convenience to please the world.
     Bible Standard
     There is danger in interfaith because it is an evidence of apostasy or departure from the Way of Life on the part of the true worshippers of God. The Bible standard is that the true Christian Faith must not be violated or compromised.
     Any church group that does not preach the truth faithfully as contained in the Bible is false. ” He that hath my word, let him speak my word FAITHFULLY”, said God, “What is the chaff to the wheat?” – Jeremiah 23: 28.
     Concerning this atomic space age, St. Paul stated: “Now the Spirit speaketh expressly, that in the latter times some shall depart from the faith, giving heed to seducing spirits, and doctrines of devils; speaking lies in hypocrisy;…forbidding to marry, and commanding to abstain from meats…” – l Timothy 4: 1-3.
     For true Christians to pray together with people of various and wrong beliefs or have fellowship with those preaching the doctrines of devils is INTERFAITH; it is spiritual fornication; it is a sin. – l Corinthians 10: 21. 22; Matthew 6: 24; James 4: 4.
     No Compromise
     Jesus Christ whose example Christians are bound to follow (John 13: 15) did not compromise his faith with those of the Pharisees and other false religionists of his time. , Rather he exposed and condemned their errors and hypocrisy. He said: “… Woe unto  you, scribes and Pharisees, hypocrites! for ye are like unto whited sepulchres, which indeed appear beautiful outward, but are within full of dead men’s bones, and of all uncleanness. Even so ye also outwardly appear righteous unto men, but within ye are full of hypocrisy and iniquity…” – Matthew 23: 23-31.
     Today, there are the counterparts of the Pharisees whose stock-in-trade is deceit: and hypocrisy – sometimes coined in a refined term as “religious diplomacy”.
     When the devil was to show up himself where Christ was doing the work of God, he (Jesus) told his disciples: “…For the prince of this world cometh, and hath nothing in me …Arise, let us go hence.” – John 14: 30, 31. Christ did NOT COMPROMISE!
     What is more, St. Paul stated: “DO: NOT UNITE yourselves with unbelievers; they are not fit mates for you. What has righteousness to do with wickedness? Can light consort with darkness? Can Christ agree with Belial, or a believer join hands with an unbeliever?. And therefore, ‘come away and leave them, separate yourselves, says the Lord; do not touch what is unclean (and lie is unclean being an abomination – Proverbs 6: 16-19) Then I will accept you, says the Lord, the Ruler of all being…” – 2 Corinthians 6: 14-18, New English Bible.
     It is on this Christian principle the God’s Kingdom Society stands. Certainly, there is no agreement between light and darkness. Truth and falsehood can never harmonize. So we uphold the banner of truth at all times, and, like Saint Paul, “renounce the hidden things of dishonesty, not walking in craftiness, nor handling the word of God deceitfully; but by manifestation of the truth commending ourselves to every man’s conscience in the sight of God.” – 2 Corinthians 4: 1, 2
     God from time has been against interfaith and has never tolerated it. The Jews who practised it were severely punished. The instance of Solomon is always remembered by serious worshippers of God. “Did not Solomon King of Israel sin by these things? yet among many nations was there no king like him, who was beloved of his God, and God made him king over all Israel: nevertheless even him did outlandish (unbelieving, strange) women cause to sin.”- Nehemiah 13: 26; 1 Kings 11: 1-14.
     For the details of how the Jews practised interfaith and how they were punished, read Psalm 106: 13-46.
     Peaceful Co-existence
     The GKS, though strongly opposed to interfaith, believes in tolerance and in peaceful co-existence with other religious groups until God’s day of decision when the tares will be destroyed by Him.-Rom. 12:17-21; Matthew 13: 1-9, 36-43.
     
     INTERFAITH IS DANGEROUS. Beware lest you fall a victim and end up in destruction from God. One becomes a victim when one believes in “the doctrines of devils” and unite oneself with those “who are not fit mates” Yes, God says “come away and leave them, separate yourselves”.`,
      title:"THE DANGER OF INTERFAITH"},
 {key:3,
     content:`IT is a vital requirement of the Christian Faith that whoever will be saved must have the accurate knowledge of the truth. This is the will of God. (1 Timothy 2: 3, 4) The claim by anybody that he believes in Jesus Christ and accepts him as his personal Saviour is not enough for salvation unless his belief is grounded on the truth.
     The word truth in the English language means that which conforms to fact and reality, or that which is not false or fictitious. So in this respect one can say the truth of a thing that happens either in the market or elsewhere, or the truth of what one has done, and so on.
     But in the context of the subject of this sermon, the meaning is spiritual and it bears a connotation that is much wider than the ordinary usage.
     In John 1: 17, it is written: “For the law was given by Moses, but grace and truth came by Jesus Christ.” The inquiring mind would want to know what this truth is.
     When Jesus Christ was addressing the believing Jews during his first advent, he said: “If ye continue in my word, then are ye my disciples indeed; and ye shall know the truth, and the truth shall make you free.” – John 8: 31, 32.
     That was not all. At the time he was arraigned before Pilate, the Roman governor, he again made reference to the truth. Said he, “My kingdom is not of this world: if my kingdom were of this world, then would my servants fight, that I should not be delivered, to the Jews: but now is my kingdom not from hence.”.. Pilate was rather curious about the claim of it Jesus Christ of having a kingdom, and so he asked: “Art thou a king then?” Instantly, Jesus answered: “Thou sayest that I am a king. To this end was I born, and for this cause came I into the world, that I should bear witness unto the truth. Everyone that is of the truth heareth my voice”. It was at this juncture Pilate further asked, “What is truth?” – Read John 18: 36-38.
     Whatever was the motive of Pilate in asking the question, it, is all the more interesting to note that it has turned to good in that the very question has been taken up with all sincerity by faithful Christian students of the Bible as a subject for diligent research into the spiritual import of the TRUTH.
     Long before the human existence of Jesus Christ on this earth, it had been prophetically written in the Psalms that “truth shall spring out of the earth; and righteousness shall look down from heaven”. – Psalm 85: 11.
     Word of God
     In a nutshell, the TRUTH, for which Jesus Christ came to this world to bear witness, is the WORD OF GOD otherwise known as the “everlasting gospel” or the “gospel of peace”. – Romans 10: 15; Ephesians 6: 15; Revelation 14: 6, 7.
     The Psalmist said that the law of God is the truth and that His word is true from the beginning. (Psalm 119: 142, 151, 160) Jesus himself confirmed that the word of God is the truth. In his prayer to the Heavenly Father on behalf of his disciples, he said: “Sanctify them through thy truth: THY WORD IS TRUTH…And for their sakes I sanctify myself, that they also might be sanctified through thy truth.” – John 17: 17-19.
     It is abundantly clear that without the knowledge of the truth no one can practise the righteousness of God or obtain salvation. It is the truth that purifies as to make. One holy; the truth instils the fear of God in the believer; it gives faith; and it gives sound wisdom and understanding that enables one to distinguish between holy and unholy, or right and wrong.
     The fact that God’s word, the truth, cleanses one from sin was further strengthened by Jesus Christ when he said to his disciples: “Now ye are clean through the word which I have spoken unto you.” (John 15: 3) And St. Paul described the word of God as water when he wrote- as to how Jesus Christ gave himself, up for the church “that he might sanctify and cleanse it with the washing of water by the word”. (Ephesians 5: 26) This is not the literal water used for baptism as some people think but the word of God, the truth.
     Because the truth warns against sin and enjoins people to follow righteousness, anyone who believes in it and translates his belief into action will of necessity put away evil and do that which is good. It is in this way the truth sanctifies or cleanses one. That is the reason why it is written in Psalm 119: 9, to wit: “Wherewithal shall, a young man cleanse his way? by taking heed thereto according to Thy (God’s) word.” And the Psalmist added: “Thy word have I hid in my heart, that I might not sin against Thee.” (Verse11).
     It is because people disregard the truth and do not pay heed to the word of God that they continue to perpetrate wicked acts. They take pleasure in sin. When they do evil they have no prick of conscience because they are destitute of the truth and consequently, the fear of God which it instils in one and which makes one eschew evil, is not in them.
     Pure Wisdom
     The wisdom which the truth imparts is far superior to any form of worldly knowledge. It is the wisdom from above which James the apostle described as “pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy”. Yes, this wisdom found only in the Bible leads one to salvation. – James. 3: 17; 2 Timothy 3: 14, 15.
     The truth is so forceful that it is able to change the whole character of a man from evil inclinations to godly thoughts and deeds. King David stated: “The law of the Lord is perfect, converting the soul: the testimony of the Lord is sure, making wise the simple. The statutes of the Lord are right. rejoicing the heart: the command of the Lord is pure, enlightening the eyes…More to be desired are they than gold, yea, than much fine gold: sweeter also than honey and the honey comb. Moreover by them is thy servant warned: and in keeping of them there is great reward.” Psalm 19: 7-11.
     St. Paul who himself also derived great benefits from his knowledge of the truth, stated: “For the word of God is quick (alive)! and powerful, and sharper than any two edged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.” – Hebrews 4: 12.
     It is all these wonderful, divine characteristics of the word of God that makes the Holy Bible, which contains it, the greatest book ever in existence in this world.
     All through history men of high reputation whose sense of spiritual value was not beclouded by devilish philosophies or evil propensities, had always acknowledged the truth of God’s word, its goodness and irresistible force.
     Concerning the Holy Bible, which contains the word of God, Abraham Lincoln had this to say: “In regard to this great book, I have but to say, it is the best gift God has given to men. All the good Saviour gave to the world was communicated through this book. But for it we could not know right from wrong. All things most desirable for man’s welfare, here and hereafter, are to be found portrayed in it.”
     And J. Edgar Hoover, a distinguished U. S. lawyer, said: “The Bible is the unfailing guide which points the way for men to the perfect life. The lessons of charity, justice, and equality which enrich its pages should be learned well by all men in order that greed, avarice, and iniquity can be blotted out.”
     The truth comprises doctrines, judgments, instructions and divine promises. The doctrines are the basis of Christian beliefs; judgments are for the discipline of the believers; the instructions are for the guidance of the Christians in following the path of life; and the promises give hope and comfort to the faithful.
     The Psalmist described the word of God as a lamp to his feet, and a light to his path. (Psalm 119: 105) And King Solomon whose wisdom, as given him by God, was remarkable, stated: “For the commandment is a lamp; and the law is light; and reproofs of instruction are the way of life.”- Proverbs 6: 23.
     For the fact that Jesus Christ is the very embodiment of the word of God, and therefore the light-bearer, he declared: “I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.” (John 8: 12) Again, he said: “I am the Way, the Truth, and the Life: no man cometh unto the Father, but by me.” – John 14: 6.
     Power of God
     The importance of the truth, which is the gospel of Christ, cannot be over emphasised. St. Paul stated that “it is the power of God unto salvation to every one that believeth…For therein is the righteousness of God revealed from faith to faith”. – Romans 1: 16, 17.
     To be ignorant of the truth, is to be under spiritual bondage. People in such a state can never know unless the scales of the blindness fall off their eyes, they even claim to be in the light but oppose the truth. The case of Saul, who became an apostle and was known as Paul, is a striking example. When he was professing Judaism-the Jewish religion-be persecuted the Christians but when he was converted and came to the knowledge of the truth, be confessed his ignorance. Said he of himself: “Who was before a blasphemer, and a persecutor, and injurious: but I obtained mercy, because I did it ignorantly in unbelief.” – 1 Timothy 1: 13.
     Some people take offence when they are told the truth; such ones need prayer so that the devil may leave them. Those who WILFULLY oppose the truth, and persecute those preaching or spreading it are wicked, and God shall destroy them. Jesus Christ told such ones in his days: “And because I tell you the truth, ye believe me not. He that is of God heareth God’s words: ye therefore hear them not, because ye are not of God.” – John 8: 43-47. And St. John said: “He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life: but the wrath of God abideth on him.” – John 3: 36. See also Luke 10: 1,2,8-12, 16; Mark 9: 42.
     Saving Gospel
     It is for the purpose of enlightening the lost sheep of God and giving them freedom from the bondage of Satan in order that they may be saved that Jesus Christ came to preach his saving gospel of truth. Concerning his mission Christ referred to Isaiah’s prophecy which fulfilled on him, to wit: “The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the broken-hearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised…” – Luke 4: 17-21; see also 2 Timothy 2: 24-26.
     And up till today, the gospel is being preached by those who know the truth in accordance with the command of Jesus Christ. – Matthew 24: 14; 28: 19.
     The truth is very precious. It must not be adulterated by way of adding lie to it and mixing it with vain traditions of men.
     The Bible says “no lie is of the truth”. (1 John 2: 21). Anyone who believes in a lie is damned. Saint Paul made it clear that those who will perish would become victims of Satan’s deceit “because they receive not the love of the truth, that they might be saved. And for this cause God shall send them strong delusion, that they should believe a lie: that they all might be damned who believed not the truth, but had pleasure in unrighteousness.” – 2 Thessalonians 2: 10-12.
     Today, in our age, some people and/or churches teach traditions of men instead of God’s doctrines in the Bible. It was because the Scribes and Pharisees acted contrary to the truth and followed men’s traditions that Jesus Christ told them: “… Thus have ye made the commandment of God of none effect by your tradition. Ye hypocrites, well did Esaias prophesy of you, saying, this people draweth nigh unto me (God) with their mouth, and honoureth me with their lips; but their heart is far from me. But in vain they do worship me, teaching for doctrines the commandments of men. – Matthew 15: 1-9.
     It is very important, therefore, that we look well before accepting and believing any teaching or doctrine from anybody no matter his religious claims, or social status, or scholastic achievement. We must be sure that anything we believe has the backing of the Scriptures, as the early Christians of Berea did, otherwise we believe or worship in vain. – Acts 17: 10- 12; see also Galatians 1: 8, 9.
     St. Paul admonished Timothy and said: “Take heed unto thyself, and unto the doctrine: continue in them: for in doing this thou shalt both save thy self, and them that hear thee.”- 1 Timothy 4: 16.
     
     Let us therefore cleave to the truth which is able to make us free from the bondage of Satan, deceits of false prophets, idolatrous commitments, superstitions and all other devices of the devil, so as to be saved by God through Jesus Christ our Lord into His perfect Kingdom of endless peace and happiness.`,
     title:"WHAT IS TRUTH?"},
 {key:4, 
    content:`THAT it is virtually impossible to preach the truth of the gospel of Christ without condemning evil or exposing falsehood is an indisputable fact. Any preaching, therefore, that does not come in conflict with the works of error is not the gospel of Jesus Christ.
    In any issue on which opinions of men differ from one another the reasonable thing to do in order to resolve it is to resort to an authority upon which all can safely rely. If it is a matter in a court of justice and a point of law is involved, a legal authority must be found in order to decide as to which of the divergent views is right. So too if it is a matter about the Christian faith, doctrine or principle, we must depend on the Holy Bible for a solution.
    The mistake many people make is that they are too prone to rush into conclusions on spiritual matters about which personal opinions are of no consequence. They do not care to ascertain as to whether the view they hold is in accord with the Word of God. It was King Solomon who said: “Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths. Be not wise in thine own eyes…” – Proverbs 3:5-7.
    The question as to whether Christians can judge or criticise one another is one of those issues about which people hold different views. Only last week, a friend told a member of the God’s Kingdom Society: “I like the GKS because they are preaching the truth. But they should preach their own without criticising other churches.” That apart, a certain clergyman, having received a copy of The Weekly Sermon, said a similar thing about the GKS but added: “The Bible says, judge not.”
    On this question of criticism or judgment, there is no support in the Scriptures for the view that Christians should not judge or criticise one another. Rather there is abundance of evidence to the contrary.
    The Text
    The text often referred to by our critics is Matthew chapter 7, verse 1, where it is written: “Judge not, that ye be not judged.”
    We agree that Jesus Christ made this statement. But the interpretation some people give to it is very wrong and misleading. Christ himself gave its interpretation in verses 2, 3, 4 and 5, but many people have not the patience to read these verses, let alone understand them. He did not mean that we should not judge or criticise at all. Rather, he meant that before we judge we should make sure that we are in a position to do so in the sense that we ourselves are free from the fault for which we judge others. For if we too are guilty of what we criticise in others, they also will in return point accusing fingers at us.
    In verse 2, Jesus continued: “For with what judgment ye judge, ye shall be judged; and with what measure ye mete, it shall be measured to you again.” This will happen when the person who judges another is equally guilty in that as he criticises or treats others so too they will do to him, he being not free.
    And in verses 3 and 4, Jesus- Christ threw more light on the point when he further said: “And why beholdest thou the mote that is in thy brother’s eye, but considerest not the beam that is in thine own eye? Or how wilt thou say to thy brother, let me pull out the mote out of thine eye; and, behold, a beam is in thine own eye?”
    It is possible some may still be in doubt as regards the intention of Christ or misconstrue the whole illustration; so he reprimanded those who always see others’ faults and not theirs, and positively stated what Christians should do, as it is written: “Thou hypocrite, first cast out the beam out of thine own eye; and then shalt thou see clearly to cast out the mote out of thy brother’s eye”
    According to the whole tenor of his illustration there is no justification whatsoever for the conclusion that Christ is against criticism. Contrariwise, it is clear that we can judge others of their errors provided we correct ourselves and put away our own. By this standard a thief is not qualified to criticize another person who steals, and an adulterer is not in a position to judge another person who commits fornication when he himself has not fully repented otherwise he will be regarded as a hypocrite.
    In support of this principle as established by Jesus Christ, St. Paul stated that whoever condemns sin in others and do the very same thing has no defence at all but condemns himself. He declares: “Therefore thou art inexcusable, O man, whosoever thou art that judges; for wherein thou judgest another, thou consdemnest thyself; for thou that judgest doest the same things” – Romans 2:1.
    Character of Jesus
    When a thing is wrong Christians should have the boldness to say it is wrong; and when they see the truth let them say it and stand by it. This was the character of Jesus Christ when he was on earth.  He criticized the Pharisees and Sadducees for their false claims and exposed their evil practices. When he crossed swords with the Sadducees on the question of resurrection, he told them bluntly: “Ye do err, not knowing the scriptures, nor the power of God.” – Matthew 22:29.
    On a certain occasion when Jesus censured the Pharisees and they took offence, his disciples asked him: “Knowest thou that the Pharisees were offended, after they heard this saying?” Christ answered at once: “Every plant, which my heavenly Father hath not planted, shall be rooted up, Let them alone: they be blind leaders of the blind. And if the blind lead the blind, both shall fall into the ditch.” – Matthew 15:12-14.
    It is because people fear to say the truth or to condemn what they know to be evil that the world is sinking more and more in iniquity. Many religious leaders who claim to be vicars, apostles, bishops, chief imams, and so forth connive at the evil doings of their followers, particularly the nobles among them, because of their tendencies of seeking to please men rather than being faithful to God.
    The tribulation in Nigeria today has been blamed on the excesses of politicians during the civilian regime. But when, among the politicians and others, there were glaring cases of oppression, bribery and corruption, adultery, mischief-making. deliberate falsehood, drunkenness and so on, what did their spiritual leaders do to rebuke their sins or evil deeds and warn them against the danger they were exposing the nation to, and God’s judgment and punishment that could eventually follow? And since trouble erupted it is these same religious leaders who adopted an attitude of dumbness over sin that are now most vocal, in their” usual act of sanctimoniousness, in a frantic bid for prayers. Can God hear our prayers when we have not repented of our sins and are not sober? “Behold, the Lord’s hand is not shortened, that it cannot save; neither his ear heavy, that it cannot bear; but your iniquities have separated between you and your God, and your sins have hid his face from you that he will not hear…” – Isaiah 59: 14.
    However, we trust that the good Lord will for His name’s sake spare this Republic so that His innocent children may have a free course to serve Him in love.
    The stand of the GKS for the truth and righteousness of God is admired by many people, but some envy and oppose her. However, the truth always prevails.
    It was interesting to note, as reported in the New Nigerian of August 24, 1966, that the Anglican Archbishop C. J. Patterson “blamed religious leaders for their studied silence” over the situation in Nigeria. He was further quoted as saying in a circular letter to his fold: “We are the devil by the weakness of our divisions which prevent us from speaking unanimously.”
    We appreciate the Archbishop’s courage for accepting blame but the excuse for their weakness is untenable. The divisions among Christians is no justifiable around for any servant of Christ to refrain from discharging his spiritual functions creditably; Unanimity of speaking is not all that is important but rectitude, forth rightness and truth notwithstanding the voice of dissent.
    Teachings
    We do not condemn personalities or individuals. We do not say that all those in other religious groups are devils, and those in the GKS are holy. What we criticize are the teachings and doings which we have found to be unscriptural and therefore erroneous.
    For instance, some teach and make people believe in purgatory whereas Jesus Christ and his early apostles did not teach any such thing. Purgatory is not found anywhere in the Bible. There are those who teach that the soul can never die; but the Bible shows clearly that the soul can die. – Psalm 89: 48; Ezekiel 18: 4; Matthew 10: 28; Acts 3; 23, etc. Others also command their priests not to marry but the Bible says that “a bishop must be the husband of one wife”. (1 Timothy 3:1,2) Certain church groups baptise infants without scriptural authority. There are a lot more that are taught and done falsely in the name of God.
    A teacher of lies is a great danger to human societies because they lead people at the instance of the devil to destruction. (Isaiah 9:16; Jeremiah 14:14; Matthew 15:14) To say that the lies of bogus preachers should not be pointed out or criticized is contrary to the will of God.  It is a duty incumbent on the true servants of Christ to warn people against false prophets. The encounter of St. Paul with Bar-Jesus, a false prophet, in his days is a case in point. St. Paul called him “the child of the devil” and “an enemy of righteousness” Addressing him St. Paul said: “Wilt thou not cease to pervert the right ways of the Lord?” The apostle then cursed him in the name and power of the Lord and the false prophet became blind. And when Sergius Paulus, a ruler, saw all that happened, he believed, being astonished at the doctrine of the Lord”  – Read Acts 13:6-13.
    If Christian must not judge one another, then those who say that the GKS is wrong for criticizing others are equally guilty for judging the GKS.
    However, the truth is that there is no church organization that does not judge others; otherwise there would have been no divisions among them. As reported in a Roman Catholic newspaper, the INDEPENDENT (Sept. 5-12, 1964, page 2) “Protestants of all kinds have strong doctrinal differences from Catholics and their orders are generally not recognized by the Catholic Church”.
    Church history is replete with incidents of atrocities committed against people because of their Christian convictions by those who purported to be the “pillar of truth” in Christendom. Why were people like John Wycliffe, John Huss, Martin Luther and a host of others branded as heretics and some of them condemned to the flames?
    Now, after hundreds of years, the Roman Catholic Church has come out to own its faults. In October 1964, the Vatican Council voted by an overwhelming majority that Roman Catholics should ask pardon from other Christians for their share in bringing about disunity. The text of a draft degree passed by the assembly by 2,076 votes to 92, called for “conversion of heart”. The text said: “All have responsibility in one way for the sins of disunity. Roman Catholics therefore ask for pardon of God and of their brethren…” Daily Times, October 8, 1964, page 7).
    The point we are making is that other religious bodies do judge and some overstepped their bounds to condemn souls to death.  But all the GKS is doing, and that with all sincerity, is that of showing the light so that the people may find the way to Christ. We will never go to the extreme of condemning people to death. God says, “Vengeance is mine” – Romans 12:19.
    Written Judgement
    The preaching of the gospel involves the pronouncing of the written judgements of God in the Bible in condemnation of all that answer to unrighteousness. Jesus said that the words he had spoken would judge men in the last day. – John 12:48.
    How can the words spoken by Christ nearly 2,000 years ago judge men in this last day? Yes, it is through the propagation of the gospel by those he has commissioned through the anointing of the Holy Spirit. Indeed, to pronounce the written judgement of God is the honour of the saints in particular, and it is also the duty of the saints’ companions who are partakers of their grace to rebuke sin. – Psalm 149: 7-9; Romans 10:13-15; 1 John 2:27; 1 Corinthians 6:1-3; Jude 14, 15; 1 Timothy 5:20, 22; 2 Timothy 4:1, 2; Titus 1:4-9; etc.
    Whenever the written judgement is preached, being the truth, it brings to light every false way and has a piercing effect against all on the side of error. St. Paul stated: “But we are sure that the judgement of God is according to truth against them which commit such things.” – Romans 2:2, see also Hebrews 4:12.
    There is always a conflict between truth and falsehood. As light exposes what is hidden in darkness so too the truth uncovers or brings to view lies, hypocrisy and all other hidden things of dishonesty. St. Paul warned the Christians to “have no fellowship with the unfruitful works of darkness, but rather reprove them”. He added: “But all things that are reproved are made manifest by the light: for whatsoever doth make manifest is light.” – Ephesians 5:11-13.
    For obvious reasons, evil men and those whose teachings are questionable do not want criticism. They always oppose and persecute those preaching the truth. That was why St. Paul said that they preached “the gospel of God with much contention” – 1 Thessalonians 2:1-4.
    There are certain church leaders who warn their adherents not to listen to the lectures of the GKS, and some even dictate to their followers not to read publications of others. Such is an attitude of those whose doctrines are not true.
    It is those who have something to hide that fear to come to the light. Jesus said: “For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved. But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God.” – John 3:20, 21.
    Any church organization that is preaching the truth will have no cause to fear judgement. The truth is quick and forceful, and it can withstand any acrid test of criticism, and triumph over everything that rises against it by the power of God. Milton, the English Puritan poet, was right when he stated, “Truth IS as ‘impossible to be soiled by any outward touch as the sunbeam”. Also an erstwhile judge of the Supreme Court of, the United States was once reported as saying, “If a religious belief has substance, it can survive criticism, heated and abusive though it may be, with the aid of truth and reason alone;” And Saint Paul in his characteristic straightforwardness wrote: “For we can do nothing against the truth, but for the truth.” – 2 Corinthians 13: 8.
    Criticisms aimed at correcting errors and reproving evils are necessary for progress. “All Scripture is given by the Inspiration of God” said St. Paul, “and is profitable for doctrine, for reproof, for Correction, for instruction in righteousness: that the man of God may be perfect, thoroughly furnished unto all good works.” – 2 Timothy 3: 16, 17.
    The only thing is that our judgment must not be malicious or based on false premises put constructive and just. Said Jesus Christ: “Judge not according to the appearance, but judge righteous judgment.” – John 7: 24.
    On the whole, it has been established beyond all reasonable doubt that Christians can judge or criticise one another in accordance with the Holy Scriptures.
    
    May God bless those who understand and appreciate the truth of His word when told – whether in the form of correction, reproof or rebuke, criticism or judgment, advice or instruction. Amen.`,
    title:"CAN CHRISTIANS JUDGE ONE ANOTHER?"},
 {key:5, 
    content:`ON the first Sunday of October every year the God’s Kingdom Society commemorates the birth of the Beloved Son of God Almighty, Jesus Christ the Righteous, as FREEDOM DAY. His birth in Bethlehem about 2,000 years ago marked a turning-point in the history of the human race.
Freedom day is not an occasion for riotous merry-making but that for sober reflections on the goodness of God for sending Jesus Christ to this evil world for the spiritual emancipation of His lost sheep. It is an occasion for meditating on the significance of the mission of Christ on earth, and for self-examination as to whether we are living up to the expectation of the Lord.
The celebration is always marked by divine services held in all branches of the GKS, and the President, Brother E. T. Otomewo, usually sends a written message that is read and explained during the services.
The following is the full text of the Freedom Day Message of the President this year:-
Members and Friends,
HAIL JEHOVAH AND JESUS CHRIST!
On this glorious occasion of the commemoration of the auspicious birth of our Lord and Saviour Jesus Christ, the greatest Advocate of freedom who has ever lived on this earth, I send you all my hearty Christian greetings and wish you the Lord’s blessings and protection!
As many of you know, we of the God’s Kingdom Society (GKS) hail the Almighty God whose name is Jehovah, and Jesus Christ, the Redeemer of mankind, because it is They only that can truly save as recorded in Psalm 3:8; Isaiah 45:21,22; John 17: 3; Acts 4:10-12; Revelation 7: 9-17.
Through the frequent criticisms of the GKS and some others, many people are now aware of the fact that Jesus Christ was not born in December but in October. I do not intend to go into details now on this issue. But suffice it to say that there is no authentic history or Bible record which says that Jesus Christ was born on December 25. Even the Roman Catholic Church has agreed with the GKS at last on this matter. A Roman Catholic magazine, The Catholic Voice, had this to say in its issue of July 1962:
“The Gospels do not mention any date for the birth of Christ. We do not know the date of Christ’s birth, not even the year in which He was born. We celebrate the feast of Christ’s birth, on the 25th of December at least in the Western Church. The Eastern Catholic Church celebrates the same feast on the 6th of January. These dates are not based on historical evidences of the exact date of Christ’s birth. The 25th of December was chosen to celebrate Christmas in the third century. . . “ (Page 110)
We shall treat the subject about the date of Christ’s birth in due course and have it published in The Weekly Sermon.
THE GOLDEN RULE
The theme of my message for the Freedom Day this year, 1968, is drawn from the remarkable and famous statement of Jesus Christ at Luke chapter 6, verse 31, to wit: “And As Ye Would That Men Should Do To You, Do Ye Also To Them Likewise.” This has been described as the Golden Rule, which, if followed or observed by men, will certainly bring peace and harmony to the world and thus fulfil to the letter the blessing of “peace and good will” bestowed upon mankind when Jesus Christ was born in: Bethlehem. On that memorable occasion, the angels of heaven chanted in praise of God, saying:
“…Glory to God in the highest, and on earth peace, good will toward men.” – Read Luke 2: 8-14.
It is clear from what we see among men and in the so-called Christian nations and/or countries of the world that the majority of the people-even among those professing Christianity-do not know Jesus Christ. In other words, they neither understand the teachings of Christ nor his way of life. Indeed, Jesus himself said: “Not everyone that saith unto me, Lord, Lord, shall enter into the kingdom of heaven; but he that doeth the will of my Father which is in heaven.” – Matthew 7: 21.
Christianity means more than oral declarations or mere attendance at services on Sundays. It must be practised in the sense of absolute submission to Jesus Christ, the only Mediator between God and men, and keeping his commandments.
Jesus Christ preached the truth of God’s word faithfully, uncompromisingly and fearlessly. He was sincere, humble, kind, forthright and godly. He loved his sheep, and for their sake he laid down his life as a ransom. “Greater love hath no man than this, that a man lay down his life for his friends,” said he. (John 15: 14).
Hypocrisy
Christ hated hypocrisy and he warned his disciples: “…Beware of the leaven of the Pharisees, which is hypocrisy.” (Luke 12: 1) But today we find that hypocrisy has become the common habit of some people who claim to be Christ’s  representatives or followers.
Where there is hypocrisy, the Golden Rule of “do ye also to them as ye would that they should do to you”, becomes meaningless. We have heard of some pastors or religious leaders who, after warning their flocks against adultery, go in the dark or in some secret corners to seduce and commit adultery with the wives of some of their followers. Some of these evil acts, as alleged, take place when the women go to the priests to make confessions, or to receive “holy” communion, or to ask for prayers.
Naturally, any or the priests who indulges in such iniquitous acts, if married, Will not want his wife to be defiled by anyone; yet he has the devilish courage to do to people what he would not want others to do to him!
You as a father will not want your daughter to be beaten up by her husband who is your son-in-law, as some often do, but you mercilessly flog your wife, another man’s daughter, in your home even for petty domestic misunderstandings! Do you, by so doing, observe the Golden Rule as laid down by Jesus Christ? Certainly not!
Your son or daughter or brother or sister just from school with the School Certificate – perhaps with a first division pass – goes to a prospective employer or a personnel manager for employment. He or she passes the interview creditably and proves competent in every respect for the job but he or she would not be employed UNLESS your son or brother offers a bribe of £20, or your daughter or sister gives up herself to be carnally defiled. No doubt, you will not be pleased – and no godly person will ever be pleased – with such an incident. But this is exactly what some people do to others, yet they call themselves Christians!
Guilty Conscience
Moreover, you as an individual will be displeased if someone slanders or back-bites you, yet many Christians so-called slander their fellow Christians. The God’s Kingdom Society has often been made an object of deliberate misrepresentations, slander and reproaches by her detractors who also (profess to be Christians.
The evils done by people are so many that one cannot enumerate all of them especially in an address such as this. Anyone who does what is bad knows in his conscience that he is doing evil; and the guilty conscience has a way of tormenting one. Indeed, John the apostle of Jesus Christ said: “For if our heart condemn us, God is greater than our heart, and knoweth all things. Beloved, if our heart condemn us not, then have we confidence toward God.”-1 John 3: 20, 21.
Those who do to others what they do not want others to do to them are not fit to hold public offices, and if they claim to be Christians, they are of the type concerning who m Jesus Christ, quoting Isaiah the prophet, said: “This people draw nigh unto me with their mouth, and honoureth me with their lips; but their heart is far from me.” – Matthew 15: 7, 8.
Yes, all such ones – bogus Christians they are – are a reproach to Jesus Christ and except they repent of their evil deeds they shall lose all their ill-gotten gains and suffer destruction from God in the end, for giving cause for the ungodly to reproach God and His church.- Isaiah 3: 11; Romans 2: 24. 25; Galatians 6: 7. 8.
As earlier stated in this message, God through His angels, blessed mankind with peace and goodwill when Jesus Christ was born. (Luke 2:14) But the fact that the whole world does not enjoy this peace and the nations are hardly of any genuine goodwill towards one another shows clearly that man has gone far away from the path of peace having, like as in the days of Noah before the flood, sunk deep into the ocean of sin. The fact of this is obvious as could be seen in the carnality and godlessness of men the world over.
The speed at which our present generation is running after sin is rising so high that there is cause for fear that it will surpass the sins of Sodom and Gomorrah because of which those cities were utterly wasted. And God warned that the fate of the sinners in Sodom and Gomorrah should serve as an example to those who love sin. – 2 Peter 2: 4-10.
Nevertheless, as God has never left Himself without a witness, there are men and women on earth today who serve Him in truth. They appreciate the fact that Jesus Christ died for their sins. This they know does not mean that they should continue to sin, but that they should deny “ungodliness and worldly lusts” and “Jive soberly, righteously, and godly, in this pre- sent world …” – Titus 2: 11-14.
Charity
Before I conclude, I will not fail to emphasize that the essence of the Golden Rule is bound up in one word – CHARITY. And charity is LOVE. This is the virtue without which no one can successfully translate the Golden Rule into action. The truth of this will be more appreciated if we lay to heart the statement of St. Paul that “he who loves his neighbour has satisfied every claim of the law”. He added: “For the commandments, ‘Thou shalt not commit adultery, thou shalt not kill, thou shalt not steal, thou shalt not covet’, and any other commandment there may be, are all summed up in the one rule, ‘Love your neighbour as yourself.’ Love cannot wrong a neighbour; therefore the whole law is summed up in love.” -Romans 13: 8-10, New English Bible.
Amplifying on the excellence of charity or love over all other gifts, the apostle, in his first letter to the Christians at Corinth, stated: “And though I bestow all my goods  to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing. Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh not evil; rejoiceth not in iniquity, but rejoiceth in the truth; beareth all things, believeth all things, hopeth all things, endureth all things…. An now abideth faith, hope, charity, these three; but the greatest of these is charity.” – 1 Corinthians chapter 13.
Truly, if we do unto others what we want them to do to us, there will be “peace, good will” and harmony everywhere in the world.

May God continue to preserve His sheep wherever they are so that they may live to worship Him in love and peace through Jesus Christ our Lord. Amen`, 
    title:"FREEDOM DAY MESSAGE (Sun. Oct. 6, 1968)"},
 {key:6, 
    content:`NO one who has a clear insight into God’s revelations as contained in the Holy Bible will ever doubt the reality of the existence of heaven. The truth of God remains unaffected though unconverted, misinformed and faithless men may doubt it.
Conflicting views have been expressed by people about heaven. Some people believe and teach that it is a place where all good men, women and even children go after death to enjoy everlasting bliss.
Religious racketeers have used their trumped up ideas of heaven to play on the ignorance of people, taking money from them with the promise and hope that whatever they spend for the church is being used in heaven to prepare a place for them. Sometimes fictitious stories of certain people carried in the arms of angels to heaven are told the flock from the pulpit with a view to making the sermons interesting as well as boosting up the economy of the church. For this same purpose the parable of Jesus Christ about Lazarus and the rich man has been given a twist and interpreted literally as if poverty is the passport to heaven. But priests are making themselves rich on earth!
In a religious magazine, THE PRAIRIE OVERCOMER, issue of January 1953, published monthly by Prairie Bible Institute, Alberta, Canada, the story of a “woman who saw heaven” was reported. The woman, as reported, “died at three o’ clock” and “her family, in accordance with Chinese custom, had immediately prepared her body for burial”. At about sunset a noise was heard in the death chamber, the report went on, and the woman was found awake sitting erect and having removed her grave clothes and put on those she had been wearing before her death. She was then quoted as saying:
“I remember seeing all the family around me crying. Then the Lord Jesus came into the room and took me by the hand and said, ‘Come with Me.’ In a short time we were before a gate of pearl. It was the gate of Heaven. Angels opened it and we went in. I saw many beautiful houses all of pretty colours…”
The report says that “people flocked in from miles around to hear the wonderful story” and “they could not reject her testimony”
We must point out that this story of the woman cannot be reconciled with the teachings of Jesus Christ whom she said took her by the hand and, therefore, the story is most unacceptable. A demon in a pretended appearance of Jesus Christ and others in the guise of angels might have appeared to her, and from her own account it is clear that she was, according to the Scriptures, a victim of evil spirits – demons. – 2 Corinthians 11: 14, 15; 1 John 4: 1; Revelation 16: 13, 14.
Ignorance
It is certain teachings of some of the churches which have neither the backing of the Scriptures nor of sound reason, that have turned some people to be agnostics and atheists believing not in God or heaven or other sacred truths. But some atheists and agnostics – the reasonable and humble ones – have become Christians after discussions, which were devoid of prejudice, with Christian leaders who preach the truth. However, we know, too, that some do not believe Christian doctrines because of their arrogance and spiritual ignorance (John 9: 39-41); and some others being devils incarnate never appreciate or understand the truth of God but always oppose it. – Psalm 10: 4, 5; Daniel 12: 10; 1 Corinthians 2: 14; 2 Corinthians 4: 3, 4.
On the other hand, there are people who argue that heaven is not a place and that it cannot be located but that it is a state or condition. They hold the view that when a person is living well in comfort, and enjoying the good things of life, he is in heaven.
A certain Englishman in Lagos who claimed to be a Christian once had a discussion with one of the ministers of the GKS about heaven. His idea of heaven was that it is a state of good living in this world, and argued that no one could point as to which direction heaven is. However, at the end of the discussion, which took place in his house on his request, he honestly confessed his ignorance of the Bible.
Under the heading of “heaven and hell”, the Illustrated World Encyclopedia has this to say: “Heaven is the name for the p1ace where good persons are rewarded after they die…People may usually think of heaven as being ‘in the sky’ and hell ‘below the earth’, but in the Christian re1igion there is no exact place where heaven or hell is known or supposed to be.” (Vol. 11, page 2539) This view which many hold is grossly erroneous.
Theologians
Even now some who claim to be theologians are doubting the existence of heaven. In the atlantic edition of the TIME magazine issue of May 19, 1967, it was reported that “many theologians are now attempting to redefine heaven and hell in this-worldly terms- not as places where humans survive after death, but as states of mind and modes of being that begin here on earth.” The magazine then quoted Notre Dame’s Jesuit Biblical Scholar, John Mc- Kenzie, as saying, “The traditional views of heaven and hell are about 95% mythology.”
Earlier in the issue of March 31, 1967, the TIME had reported that heaven and hell were shrugged off as myth by Dominican Theologian Willem van der Marck. He was quoted as saying, “Heaven and hell just do not preoccupy us any more:”
Here in Nigeria there are also many people who do not believe that there is heaven. In the DRUM magazine, issue of December 1966 the views of some Nigerians about God were published. One of those interviewed was reported to said: “I do not believe that is God who sits in to heaven watch what we do. Neither do believe that there is a place like heaven…
It is rather amusing to go through this cross-section of views of sceptical men most of which smack of crass spiritual ignorance or delusion.
We do know that God’s knowledge is infinite – that is, it has no end. But the human intellect has a limit, and so spiritual matters or things that are beyond that limit can never be comprehended by men – no matter how highly developed their reasoning faculty may be. This is the cause of the difficulties of people over spiritual matters. Said St. Paul: “…We speak, not in the words which man’s wisdom teacheth; but which the Holy Ghost teacheth; comparing spiritual things with spiritual. But the natural man receiveth not the things of the Spirit of God; for they are foolishness unto him; neither can he know them, because they are spiritually discerned.” – 1 Corinthians 2:13, 14.
Moreover, unless a person has pleasure in the word of God and allows himself to be used by Him through His Spirit as to be able to compare spiritual things with spiritual, he cannot understand His works. The Psalmist declared: “The works of the Lord are great, sought out of all them that have pleasure therein.” – Psalm 111: 2.
Men have developed a tendency of discarding or disbelieving what they have not the capacity to understand. Concerning God and His works, it is such things as are revealed that we as human beings – imperfect mortals – can know. It was Moses the prophet who said: “The secret things belong unto the Lord our God: but those things which are revealed belong unto us and to our children for ever, that we may do all the words of this law.” – Deuteronomy 29: 29.
Unquestionable Truth
That heaven is a place is an unquestionable truth revealed in the Holy Bible. Where it is, is so clearly shown in the Bible that even a child with little training can point to its direction. It is not a state of the mind or a condition of living. The Bible account of the creation gives a vivid picture of what and where heaven is.
In Genesis chapter 1, verse 1, it is written: “In the beginning God created the heaven and the earth,” The earth was void, there was no form of life, and it was covered with waters. There was darkness all over the earth until light was created. After that, the firmament was also created. “And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament and it was so. And God called the firmament Heaven.” – Genesis I: 6-8.
The account further states of how the sun, moon and stars were created and placed in the expanse of heaven. “And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also, And God set them in the firmament of the heaven to give light upon the earth.” – Genesis I: 16, 17.
In the face of the foregoing glaring biblical record, it will be unreasonable not to think of heaven as a place or to pretend not to know its location. We standing on this earth cannot point downwards when we talk of the firmament or where the sun, moon and stars are: we must look or point skywards or upwards.
The word heaven is defined as high or lofty. Thus the cloudy region of the air where birds fly is spoken of as heaven. It is stated that God created “fowls that may fly above the earth in the open firmament of heaven.” (Genesis I:20) And Elihu in the book of Job spoke of the birds as “the fowls of heaven.” (Job 35 : 11).
There is, above the firmament, a vast open space where other planets, the sun, moon and stars. are. And yet above all that there is the heaven where the Almighty God dwells. In the Psalms it is written: “The heaven, even the heavens, are the Lord’s: but the earth hath he given to the children of men.” “The Lord is in his holy temple, the Lord’s throne IS IN HEAVEN: his eyes behold, his eyelids try, the children of men.” (Ps.115: 16; 11: 4). Heaven is again clearly shown here to be a place; not a state or condition of one’s living.
The prophet Isaiah wrote: “Thus saith the Lord, The heaven is my throne, and the earth is my footstool…” (Isaiah 66: 1; Acts 7: 47-50.) And in the Lord’s Prayer, we say: ‘,Our Father which art in heaven, Hallowed be thy name” (Matthew: 6 : 9) Jesus Christ teaches us by this that our gracious Spirit Father is in a place called heaven.
Heaven of heavens
The Bible shows that there are several heavens but the heaven where God dwells is the highest and is known as “the heaven of heavens”. (Deuteronomy 10: 14; 1 Kings 8:27; 2 Chronicles 2:6) Also, innumerable angels are there. These are spirit creatures who in intelligence, power and in every other respect, are far superior to human beings. (Psalm 8: 3-5; 103: 20; Hebrew 12: 22,23) It was from heaven Jesus Christ came to this earth, and he said: “For I came down from heaven, not to do mine own will, but the will of him that sent me.”
Indeed, that heaven is a place and is above is therefore beyond argument. Jesus Christ ascended to heaven in the presence of his apostles after he had spoken to them. The Bible states that while they looked at him. “he was taken up; and a cloud received him out of their sight. And while they looked steadfastly toward heaven as he went up, behold, two men (angels of God) stood by them in white apparel…” The angels told them that “Jesus is taken up from you into heaven” – Acts 1: 9-11. And St. Paul confirmed that Jesus Christ “ascended up far above all heavens” – that is, the highest heaven or heaven of heavens.-  Ephesians 4: 10: Hebrews 4: 14; 8: 1, etc.
From all the references of the Bible already explained, it is erroneous to hold the view that heaven does not exist or that it cannot be located. But the question as to who will go to heaven is another subject that will be treated in due course. However, we must point out that the teaching that all good persons go to heaven when they die is without foundation in the Scriptures. If all the good will go to heaven, why did the Psalmist and Jesus Christ say that “the meek shall inherit the earth”? So too the belief that Mary went to heaven with the human body is a figment of imagination.
If Christian teachers confine themselves to teaching what God says in the Bible, people will not be as ignorant of the Scriptures as they are today. They put aside the Bible and teach fables to misguide innocent people.
The view that there are seven heavens cannot be substantiated with the Scriptures. The Bible gives the idea of three heavens. St. Paul in his second epistle to the Corinthians wrote about the visions and revelations of the Lord, saying, “I knew a man in Christ above fourteen years ago, (whether in the body, I cannot tell; or whether out of the body, I cannot tell: God knoweth;) such an one caught up to the THIRD HEAVEN.” – 2 Corinthians 12: 1,2.
It is very important that we believe that there is heaven where God Almighty dwells and from where we should expect protection and blessing particularly in this atomic age. Where we do not, then we are no Christians and have no protection or hope of salvation. It was James the apostle who stated: “Do not err, my beloved brethren. Every good gift and every perfect gift is from above (Heaven), and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.” – James 1: 16, 17.
Yes, heaven is a place and it is there God in His Kingdom dwells!`, 
    title:"WHAT AND WHERE IS HEAVEN?"},
 {key:7, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:8, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:9, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:10, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:11, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:12, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:13, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:14, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:15, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"},
 {key:16, 
    content:"this is the first name of this app is temple efe", 
    title:"sermon name"}
 
]

module.exports = SermonDetails;
