const State = [
    {state:'Abia',key:1},
    {state:'Adamawa',key:2},
    {state:'Akwa Ibom',key:3},
    {state:'Anambra',key:4},
    {state:'Bauchi',key:5},
    {state:'Bayelsa',key:6},
    {state:'Benue',key:7},
    {state:'Borno',key:8},
    {state:'Cross River',key:9},
    {state:'Delta',key:10},
    {state:' Ebonyi',key:11},
    {state:'Edo',key:12},
    {state:'Ekiti',key:13},
    {state:'Enugu',key:14},
    {state:'Gombe',key:15},
    {state:'Imo',key:16},
    {state:'Jigawa',key:17},
    {state:'Kaduna',key:18},
    {state:'Kano',key:19},
    {state:'Katsina',key:20},
    {state:'Kebbi',key:21},
    {state:'Kogi',key:22},
    {state:'Kwara',key:23},
    {state:'Lagos',key:24},
    {state:'Nasarawa',key:25},
    {state:'Niger',key:26},
    {state:'Ogun',key:27},
    {state:'Ondo',key:28},
    {state:'Oyo',key:29},
    {state:'Plateau',key:30},
    {state:'Rivers',key:31},
    {state:'Sokoto',key:32},
    {state:'Taraba',key:33},
    {state:'Yobe',key:34},
    {state:'Zamfara',key:35},


]
module.exports = State;